# Generated by Django 3.1.3 on 2020-11-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
