# Generated by Django 3.1.3 on 2020-11-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parsing', '0003_auto_20201124_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
