# Generated by Django 3.1.3 on 2020-11-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parsing', '0004_auto_20201125_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_ref',
            field=models.CharField(max_length=50),
        ),
    ]
