# Generated by Django 3.1.3 on 2020-11-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_parsing', '0005_auto_20201125_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_products', to='data_parsing.entry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parsing.product')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='products',
            field=models.ManyToManyField(through='data_parsing.ProductInEntry', to='data_parsing.Product'),
        ),
    ]
