# Generated by Django 3.1.3 on 2020-11-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parsing', '0007_auto_20201126_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateField(),
        ),
    ]
